### ISSUE TITLE
Jesp meta table PK too big for UTF-8 databases

### ISSUE THREAD

**Issue by patmooney** [jeteve/App-JESP#7]
Hello the curators of the great Jesp package!

It seems that the PK of the jesp meta table has a PK of VARCHAR(512) which equates to 1024 bytes in a UTF-8 DB... the PK limit on mysql 5.6 is 767 bytes.

```
    CREATE DATABASE MyDB DEFAULT CHARSET UTF8;

    ....

    ./jesp deploy
    

    Specified key was too long; max key length is 767 bytes at /.../App/JESP.pm line 276
````

**Comment by jeteve** [comment]
Boooooo MySQL 5.6

Thing is the meta patches are (well, there's only one for now) written in standard SQL, so changing it across the board is not an option.

In `_build_meta_patches`, you could test for MySQL from the DBH ( `$self->dbix_simple->dbh()` ), and output a 'MySQL 5.6' specific patch.

It should probably be something like: ` ID VARCHAR(512) CHARACTER SET latin1  ` to avoid this 767 bytes issue.

**Comment by jeteve** [comment]
Any success?

**Comment by patmooney** [comment]
the owners of this repo just don't care x
